done
mate-academy/react_movies-list-js pull request #133
Opened 2023-07-21 17:39 UTC by maxonshev

https://maxonshev.github.io/react_movies-list-js/

2023-07-22 06:36 UTC, loralevitska requested changes
Almost perfect) Let's improve

2023-07-22 06:36 UTC, loralevitska commented on src/components/MovieCard/MovieCard.jsx
> +export const MovieCard = ({ movie }) => (
Destructure `movie`

2023-07-22 06:36 UTC, loralevitska commented on src/components/MovieCard/MovieCard.jsx
> +            data-cy="MovieLink"
Always open links in new tab, use [target - blank](https://www.w3schools.com/tags/att_a_target.asp)

2023-07-22 06:36 UTC, loralevitska commented on src/components/MovieList/MovieList.jsx
> +  </div>
Use semantic tags for list `ul` `li`. Don't forget to remove default `li` dots and `ul` paddings

2023-07-22 06:36 UTC, loralevitska commented on src/components/MovieList/MovieList.jsx
> +
Remove redundant empty line

2023-07-23 06:20 UTC, etojeDenys approved these changes
lgtm

2025-03-07 10:43 UTC, closed without merging