add solution
mate-academy/react_movies-list-js pull request #2
Opened 2023-06-25 19:17 UTC by CasioPayYeah

https://casiopayyeah.github.io/react_movies-list-js/

2023-06-28 06:20 UTC, tetiana-ivanchenko requested changes

2023-06-28 06:20 UTC, tetiana-ivanchenko commented on src/App.jsx
> +import {MovieList} from "./components/MovieList";
```suggestion
import { MovieList } from "./components/MovieList";
```

2023-06-28 06:20 UTC, tetiana-ivanchenko commented on src/components/MovieCard/MovieCard.jsx
> +            src={movie.imgUrl}
use destructure assign

2023-06-28 06:20 UTC, tetiana-ivanchenko commented on src/components/MovieCard/MovieCard.jsx
> +  <>
redundant wrapper

2023-06-28 06:20 UTC, tetiana-ivanchenko commented on src/components/MovieList/MovieList.jsx
> +  <>
redundant wrapper

2023-06-28 23:03 UTC, eleonora-demikh requested changes
Good job. Just a few little things to fix

2023-06-29 16:23 UTC, ManoylovAC requested changes
Good work
Please improve your code style to establish a good habit

2023-06-29 16:50 UTC, CasioPayYeah commented on src/components/MovieCard/MovieCard.jsx
> +  const { title, description, imgUrl, imdbUrl } = movie;
> +1 to previous comment about preferable way of writing destructuring with several properties
Why is it better

`const { title, description, imgUrl, imdbUrl } = movie;`

than this
```
export const MovieCard = ({
  movie: {
    title,
    description,
    imgUrl,
    imdbUrl,
  },
})
```

2023-07-03 06:20 UTC, YegorKorenkov approved these changes
Good job!

2026-05-18 14:31 UTC, closed without merging