create MovieList and MovieCard components
mate-academy/react_movies-list-js pull request #236
Opened 2023-08-22 17:01 UTC by rostyslav48

https://rostyslav48.github.io/react_movies-list-js/

2023-08-22 17:19 UTC, serkrops approved these changes
LOOKS GOOD!

2023-08-23 08:37 UTC, Moroz-Dmytro requested changes
Looks good 👍 
But demo doesn't work

2023-08-23 08:37 UTC, Moroz-Dmytro commented on src/components/MovieList/MovieList.jsx
> +    )) }
```suggestion
    {movies.map(movie => (
      <MovieCard key={movie.imdbId} movie={movie} />
    ))}
```

2023-08-23 08:55 UTC, rostyslav48 commented
The demo link has been fixed)

2023-08-23 08:56 UTC, Moroz-Dmytro approved these changes

2025-08-31 20:11 UTC, closed without merging