Movies_List
mate-academy/react_movies-list-js pull request #277
Opened 2023-08-25 15:51 UTC by stunnerboyone

- [DEMO LINK] (https://stunnerboyone.github.io/react_movies-list-js/)

2023-08-25 17:20 UTC, Andriy-Shymkiv requested changes

2023-08-25 17:20 UTC, Andriy-Shymkiv commented on src/App.jsx
>  // import moviesFromServer from './api/movies.json';
remove comments

2023-08-25 17:20 UTC, Andriy-Shymkiv commented on src/components/MovieList/MovieList.jsx
> +  <>
redundant fragment

2023-08-25 17:20 UTC, Andriy-Shymkiv commented on src/components/MovieCard/MovieCard.jsx
> +  <>
redundant fragment

2023-08-25 17:21 UTC, loralevitska requested changes
Almost perfect) Let's improve
- remove the space to refactor link format
![image](https://github.com/mate-academy/react_movies-list-js/assets/70009205/39c86cc6-807e-4705-9913-7127d2c1ba15)

2023-08-25 17:21 UTC, loralevitska commented on src/components/MovieCard/MovieCard.jsx
> +            src={movie.imgUrl}
Destructure `movie`

2023-08-25 17:21 UTC, loralevitska commented on src/components/MovieList/MovieList.jsx
> +        <MovieCard movie={movie} key={movie.imdbId} />
Destructure `movie`

2023-08-25 17:21 UTC, loralevitska commented on src/components/MovieCard/MovieCard.jsx
> +          <a href={movie.imdbUrl} data-cy="MovieLink">
Always open links in new tab

2023-08-27 07:26 UTC, TarasHoliuk approved these changes

2023-11-21 19:13 UTC, closed without merging